#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZOTDIR:-$HOME}/.shell_secrets" ]]; then
  source "${ZOTDIR:-$HOME}/.shell_secrets"
fi

bindkey "^R" history-incremental-search-backward

autoload -Uz promptinit
promptinit
prompt paradox

alias gcd='cd `git rev-parse --show-toplevel`'

export GOPATH=${ZOTDIR:-$HOME}/Code/golang
export PATH=${GOPATH}/bin:${PATH}

if [ -d ~/.bin ]; then
  export PATH=$PATH:~/.bin
fi
